---
- name: install Docker
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Update the apt package index
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
      tags:
        - docker

    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
          - gpg
        state: latest
        update_cache: true
      tags:
        - docker

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present
      tags:
        - docker

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
      tags:
        - docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
      tags:
        - docker

    - name: Remove Containerd config
      ansible.builtin.file:
        path: /etc/containerd/config.toml
        state: absent
      tags:
        - docker

    - name: Restart Containerd
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: containerd
      tags:
        - docker

    - name: Restart Docker
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: docker
      tags:
        - docker

    - name: Add User to docker group
      user:
        name: "{{ ansible_env.SUDO_USER }}"
        groups: docker
        append: yes
      tags:
        - docker

